<p>&nbsp;</p>
<p style="margin:0cm;margin-bottom:.0001pt;line-height:13.5pt"><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">At<span class="apple-converted-space">&nbsp;</span>RudraBlessings.com<span class="apple-converted-space">&nbsp;</span>your privacy is our priority. We are committed to protecting your privacy at all times, in all situations. The information we collect about you when you become a member is used to process your orders and to provide a more personalized experience on our site. We have implemented many security policies and conditions to help protect your confidential information.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">&nbsp;</span><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><strong><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">How Do We Use the Information We Collect?</span></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">&nbsp;</span></p>
<p style="margin:0cm;margin-bottom:.0001pt;line-height:13.5pt"><b><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">When you become a member or when you will any other forms on our website.</span></b></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">When you become a member, we ask you to fill out a form that requests your name, address and e-mail address as well as some demographic information such as gender and date of birth.<br />
RudraBlessings.com will<span class="apple-converted-space">&nbsp;</span><strong>NOT</strong><span class="apple-converted-space">&nbsp;</span>share data with trusted partners to help us perform statistical analysis.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">Your name and address information is used solely to process orders unless your prior consent is given. Without your consent, this information will<span class="apple-converted-space">&nbsp;</span><b>NEVER</b><span class="apple-converted-space">&nbsp;</span>be sold, given, rented or traded to others for purposes other than order fulfillment.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">Your demographic information (gender, date of birth, etc.) will be used for several security purposes, to ensure you are who you say you are and in fact you are paying with your credit cards and not someone using your stolen credit cards.</span></p>
<p style="margin:0cm;margin-bottom:.0001pt;line-height:13.5pt"><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">&nbsp;</span></p>
<p style="margin:0cm;margin-bottom:.0001pt;line-height:13.5pt"><b><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">Your credit card/ debit card Information</span></b></p>
<p style="margin:0cm;margin-bottom:.0001pt;line-height:13.5pt"><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">We do not have any control over your credit / debit card information as the entire information lies safe with our partner payment gateways ccavenue &amp; paypal. This information is not shared with us.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">&nbsp;</span></p>
<p style="margin:0cm;margin-bottom:.0001pt;line-height:13.5pt"><strong><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">Our Use of Log Files</span></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; "><br />
When you visit our site we automatically log your IP address, your browser type and your access times. We utilize this information to conduct site performance evaluations, to see where visitors are coming from and to keep track of click stream data (the screens our users visit on our site). This data helps us to determine what content our members find most appealing so that we can maximize your enjoyment of the site. Log files are not tied to personally identifiable information.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><strong><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">Site Security</span></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; "><br />
All<span class="apple-converted-space">&nbsp;</span>our employees take your personal information very seriously. All employees must learn and obey our security policies. Access to member personal information is limited to key management personnel. The information is ID and password protected and our Web security is reviewed on a monthly basis. Your personal password is at no time revealed to any of our employees since it is in encrypted form.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><strong><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">Correcting/Updating Your Personal Information</span></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; "><br />
After becoming a subscriber you may correct/update your personal information by clicking on the 'My Account' link at the top or bottom of any page, entering your user ID (email address) and password when prompted and clicking the Edit Information button. The changes you make will be reflected in our databases instantly. If you wish to deactivate your account, you may contact our support team through <b>contact us</b> section.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">&nbsp;</span><span style="font-family: Verdana, sans-serif; font-size: 9pt; line-height: 13.5pt; ">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><strong><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">Links To Other Sites</span></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; "><br />
This Web site may contain links to other Web sites. Please note that when you click on one of these links, you may be leaving the<span class="apple-converted-space">&nbsp;</span>RudraBlessings.com<span class="apple-converted-space">&nbsp;</span>website and entering another website. These sites may independently collect or request information about you and we encourage you to read the privacy statements of these linked sites as their privacy policy may differ from ours.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><strong><span style="font-size: 9pt; font-family: Verdana,sans-serif;">Communication</span></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; "><br />
From time to time we may send out email messages alerting you that products are available, to remind you about providing feedback or for promotional offers. In addition, you will receive communication from us 1) if you contact us for a particular reason, 2) to receive your orders communications and shipping updates, or 3) we need to contact you for administrative purposes. Administrative e-mails will not contain promotional materials. If you wish to opt-out from our News Letters, you can do so at any time by using the &quot;Newsletter Unsubscribe&quot;<span class="apple-converted-space">&nbsp;</span>from the Navigation menu on any page.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><strong><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">Our Use of Cookies</span></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; "><br />
Cookies are pieces of information that your browser stores on your computer's hard drive which identify you when you enter. The ability to select samples on our site is not cookie-driven. We may use session cookies to provide a seamless experience on the site and to combine with our log files so that we can understand our site traffic and analyze our demographic information in aggregate form. If you have set your browser to reject cookies, our site will not identify you when you enter and you will need to manually type in your ID and password.</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">&nbsp;</span></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><strong><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">Your Feedback is Always Welcome</span></strong></p>
<p style="margin: 0cm 0cm 0.0001pt; line-height: 13.5pt; "><span style="font-size: 9pt; font-family: Verdana, sans-serif; "><br />
We welcome your comments and questions about our privacy policy - or anything else you might want to talk about. To contact us, you could mail us on <a href="mailto:rudrablessings@hotmail.com">rudrablessings@hotmail.com</a></span></p>
<p style="margin:0cm;margin-bottom:.0001pt;line-height:13.5pt"><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">&nbsp;</span></p>
<p><span style="font-size: 9pt; font-family: Verdana, sans-serif; ">There could be timely changes to the privacy policy without any pre notifications, for timely updates you could keep viewing this page periodically</span></p>